name: Test

on:
  workflow_call:
      
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: keinos/sqlite3:latest
    steps:
      - name: Download the output from previous steps.
        uses: actions/download-artifact@v3
      - name: Do whatever you need
        run: |
          cat myfile.txt;
          echo "Test finished";